# Form implementation generated from reading ui file 'PyQt_UIs/Add_Window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDate
import Saving

class Ui_Add_Window(object):
    
    def get_info(self):
        correctDate = self.calendarWidget.selectedDate().toString("dd.MM.yyyy")

        FullSaveData = {
            "Task Title": self.lineEdit.text(),
            "Task Description": self.textEdit.toPlainText(),
            "Task End Date": correctDate,
            "Task Priority": self.comboBox.currentText(),
            "Task Status": self.comboBox_2.currentText()
        }
        Saving.AddSave(FullSaveData)

        #print(QDate.fromString(correctDate, "dd.MM.yyyy"))

    def setupUi(self, Add_Window):
        Add_Window.setObjectName("Add_Window")
        Add_Window.resize(415, 688)
        self.label = QtWidgets.QLabel(parent=Add_Window)
        self.label.setGeometry(QtCore.QRect(10, -10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Add_Window)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 391, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(parent=Add_Window)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(parent=Add_Window)
        self.textEdit.setGeometry(QtCore.QRect(10, 120, 391, 91))
        self.textEdit.setObjectName("textEdit")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Add_Window)
        self.calendarWidget.setGeometry(QtCore.QRect(50, 270, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_3 = QtWidgets.QLabel(parent=Add_Window)
        self.label_3.setGeometry(QtCore.QRect(100, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Add_Window)
        self.label_4.setGeometry(QtCore.QRect(80, 460, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Add_Window)
        self.label_5.setGeometry(QtCore.QRect(260, 460, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(parent=Add_Window)
        self.comboBox.setGeometry(QtCore.QRect(50, 510, 111, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(parent=Add_Window)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 510, 111, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton = QtWidgets.QPushButton(parent=Add_Window, clicked=lambda: Add_Window.close())
        self.pushButton.setGeometry(QtCore.QRect(10, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Add_Window, clicked=lambda: self.get_info())
        self.pushButton_2.clicked.connect(lambda: Add_Window.close())
        self.pushButton_2.setGeometry(QtCore.QRect(270, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Add_Window)
        QtCore.QMetaObject.connectSlotsByName(Add_Window)

    def retranslateUi(self, Add_Window):
        _translate = QtCore.QCoreApplication.translate
        Add_Window.setWindowTitle(_translate("Add_Window", "Dialog"))
        self.label.setText(_translate("Add_Window", "Titel:"))
        self.lineEdit.setText(_translate("Add_Window", "Test"))
        self.label_2.setText(_translate("Add_Window", "Beschreibung:"))
        self.textEdit.setHtml(_translate("Add_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TEst</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">testt</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Add_Window", "Geplantes Enddatum:"))
        self.label_4.setText(_translate("Add_Window", "Titel:"))
        self.label_5.setText(_translate("Add_Window", "Titel:"))
        self.comboBox.setItemText(0, _translate("Add_Window", "1 - High"))
        self.comboBox.setItemText(1, _translate("Add_Window", "2 - Medium"))
        self.comboBox.setItemText(2, _translate("Add_Window", "3 - Low"))
        self.comboBox_2.setItemText(0, _translate("Add_Window", "To Do"))
        self.comboBox_2.setItemText(1, _translate("Add_Window", "In Arbeit"))
        self.comboBox_2.setItemText(2, _translate("Add_Window", "Fertig"))
        self.pushButton.setText(_translate("Add_Window", "close"))
        self.pushButton_2.setText(_translate("Add_Window", "save"))
