# Form implementation generated from reading ui file 'PyQt_UIs\Add_Window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import Saving

class Ui_Add_Window(object):

    def get_info(self):
        correctDate = self.AddEndDatumKalender.selectedDate().toString("dd.MM.yyyy")

        if self.AddFokusCheck.isChecked():
            FokusDate = self.AddFokusKalender.selectedDate().toString("dd.MM.yyyy")
        else:
            FokusDate = ""

        FullSaveData = {
            "Task Title": self.AddTitelInput.text(),
            "Task Description": self.AddBeschreibungInput.toPlainText(),
            "Task End Date": correctDate,
            "Task Fokus Date": FokusDate,
            "Task Priority": self.AddPrioAuswahl.currentText(),
            "Task Status": self.AddStatusAsuwahl.currentText()
        }
        Saving.AddSave(FullSaveData)

        #print(QDate.fromString(correctDate, "dd.MM.yyyy"))

    def setupUi(self, Add_Window):
        Add_Window.setObjectName("Add_Window")
        Add_Window.resize(676, 688)
        self.AddTitel = QtWidgets.QLabel(parent=Add_Window)
        self.AddTitel.setGeometry(QtCore.QRect(310, -10, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddTitel.setFont(font)
        self.AddTitel.setObjectName("AddTitel")
        self.AddTitelInput = QtWidgets.QLineEdit(parent=Add_Window)
        self.AddTitelInput.setGeometry(QtCore.QRect(10, 40, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddTitelInput.setFont(font)
        self.AddTitelInput.setText("")
        self.AddTitelInput.setObjectName("AddTitelInput")
        self.AddBeschreibungTitel = QtWidgets.QLabel(parent=Add_Window)
        self.AddBeschreibungTitel.setGeometry(QtCore.QRect(280, 70, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddBeschreibungTitel.setFont(font)
        self.AddBeschreibungTitel.setObjectName("AddBeschreibungTitel")
        self.AddBeschreibungInput = QtWidgets.QTextEdit(parent=Add_Window)
        self.AddBeschreibungInput.setGeometry(QtCore.QRect(10, 120, 651, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddBeschreibungInput.setFont(font)
        self.AddBeschreibungInput.setObjectName("AddBeschreibungInput")
        self.AddEndDatumKalender = QtWidgets.QCalendarWidget(parent=Add_Window)
        self.AddEndDatumKalender.setGeometry(QtCore.QRect(20, 270, 312, 183))
        self.AddEndDatumKalender.setObjectName("AddEndDatumKalender")
        self.AddEnddatumTitel = QtWidgets.QLabel(parent=Add_Window)
        self.AddEnddatumTitel.setGeometry(QtCore.QRect(70, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddEnddatumTitel.setFont(font)
        self.AddEnddatumTitel.setObjectName("AddEnddatumTitel")
        self.AddPrioTitel = QtWidgets.QLabel(parent=Add_Window)
        self.AddPrioTitel.setGeometry(QtCore.QRect(40, 480, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddPrioTitel.setFont(font)
        self.AddPrioTitel.setObjectName("AddPrioTitel")
        self.AddStatusTitel = QtWidgets.QLabel(parent=Add_Window)
        self.AddStatusTitel.setGeometry(QtCore.QRect(200, 480, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddStatusTitel.setFont(font)
        self.AddStatusTitel.setObjectName("AddStatusTitel")
        self.AddPrioAuswahl = QtWidgets.QComboBox(parent=Add_Window)
        self.AddPrioAuswahl.setGeometry(QtCore.QRect(30, 510, 111, 31))
        self.AddPrioAuswahl.setObjectName("AddPrioAuswahl")
        self.AddPrioAuswahl.addItem("")
        self.AddPrioAuswahl.setItemText(0, "")
        self.AddPrioAuswahl.addItem("")
        self.AddPrioAuswahl.addItem("")
        self.AddPrioAuswahl.addItem("")
        self.AddStatusAsuwahl = QtWidgets.QComboBox(parent=Add_Window)
        self.AddStatusAsuwahl.setGeometry(QtCore.QRect(180, 510, 111, 31))
        self.AddStatusAsuwahl.setObjectName("AddStatusAsuwahl")
        self.AddStatusAsuwahl.addItem("")
        self.AddStatusAsuwahl.setItemText(0, "")
        self.AddStatusAsuwahl.addItem("")
        self.AddStatusAsuwahl.addItem("")
        self.AddStatusAsuwahl.addItem("")
        self.AddCloseButton = QtWidgets.QPushButton(parent=Add_Window, clicked=lambda: Add_Window.close())
        self.AddCloseButton.setGeometry(QtCore.QRect(330, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AddCloseButton.setFont(font)
        self.AddCloseButton.setObjectName("AddCloseButton")
        self.AddSaveButton = QtWidgets.QPushButton(parent=Add_Window, clicked=lambda: self.get_info())
        self.AddSaveButton.setGeometry(QtCore.QRect(530, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AddSaveButton.setFont(font)
        self.AddSaveButton.setObjectName("AddSaveButton")
        self.AddFokusCheck = QtWidgets.QCheckBox(parent=Add_Window)
        self.AddFokusCheck.setGeometry(QtCore.QRect(400, 500, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AddFokusCheck.setFont(font)
        self.AddFokusCheck.setObjectName("AddFokusCheck")
        self.AddFokusKalender = QtWidgets.QCalendarWidget(parent=Add_Window)
        self.AddFokusKalender.setGeometry(QtCore.QRect(350, 270, 312, 183))
        self.AddFokusKalender.setObjectName("AddFokusKalender")
        self.AddFokusDatumTitel = QtWidgets.QLabel(parent=Add_Window)
        self.AddFokusDatumTitel.setGeometry(QtCore.QRect(440, 210, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddFokusDatumTitel.setFont(font)
        self.AddFokusDatumTitel.setObjectName("AddFokusDatumTitel")

        self.retranslateUi(Add_Window)
        QtCore.QMetaObject.connectSlotsByName(Add_Window)

    def retranslateUi(self, Add_Window):
        _translate = QtCore.QCoreApplication.translate
        Add_Window.setWindowTitle(_translate("Add_Window", "Dialog"))
        self.AddTitel.setText(_translate("Add_Window", "Titel:"))
        self.AddBeschreibungTitel.setText(_translate("Add_Window", "Beschreibung:"))
        self.AddBeschreibungInput.setHtml(_translate("Add_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AddEnddatumTitel.setText(_translate("Add_Window", "Geplantes Enddatum:"))
        self.AddPrioTitel.setText(_translate("Add_Window", "Priorität:"))
        self.AddStatusTitel.setText(_translate("Add_Window", "Status:"))
        self.AddPrioAuswahl.setItemText(1, _translate("Add_Window", "1 - High"))
        self.AddPrioAuswahl.setItemText(2, _translate("Add_Window", "2 - Medium"))
        self.AddPrioAuswahl.setItemText(3, _translate("Add_Window", "3 - Low"))
        self.AddStatusAsuwahl.setItemText(1, _translate("Add_Window", "To Do"))
        self.AddStatusAsuwahl.setItemText(2, _translate("Add_Window", "In Arbeit"))
        self.AddStatusAsuwahl.setItemText(3, _translate("Add_Window", "Fertig"))
        self.AddCloseButton.setText(_translate("Add_Window", "Schließen"))
        self.AddSaveButton.setText(_translate("Add_Window", "Speichern"))
        self.AddFokusCheck.setText(_translate("Add_Window", "Fokus Datum hinzufügen"))
        self.AddFokusDatumTitel.setText(_translate("Add_Window", "Fokus Datum:"))
