# Form implementation generated from reading ui file 'DesignedUIs/Add_Window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import Saving


class Ui_Add_Window(object):

    def get_info(self):
        correctDate = self.AddDatumInput.selectedDate().toString("dd.MM.yyyy")

        FullSaveData = {
            "Task Title": self.AddTitelInput.text(),
            "Task Description": self.AddBeschreibungsInput.toPlainText(),
            "Task End Date": correctDate,
            "Task Priority": self.AddPrioInput.currentText(),
            "Task Status": self.AddStatusInput.currentText()
        }
        Saving.AddSave(FullSaveData)

        #print(QDate.fromString(correctDate, "dd.MM.yyyy"))


    def setupUi(self, Add_Window):
        Add_Window.setObjectName("Add_Window")
        Add_Window.resize(415, 688)
        self.AddTitelText = QtWidgets.QLabel(parent=Add_Window)
        self.AddTitelText.setGeometry(QtCore.QRect(10, -10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddTitelText.setFont(font)
        self.AddTitelText.setObjectName("AddTitelText")
        self.AddTitelInput = QtWidgets.QLineEdit(parent=Add_Window)
        self.AddTitelInput.setGeometry(QtCore.QRect(10, 40, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddTitelInput.setFont(font)
        self.AddTitelInput.setText("")
        self.AddTitelInput.setObjectName("AddTitelInput")
        self.AddBeschreibungsText = QtWidgets.QLabel(parent=Add_Window)
        self.AddBeschreibungsText.setGeometry(QtCore.QRect(10, 70, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddBeschreibungsText.setFont(font)
        self.AddBeschreibungsText.setObjectName("AddBeschreibungsText")
        self.AddBeschreibungsInput = QtWidgets.QTextEdit(parent=Add_Window)
        self.AddBeschreibungsInput.setGeometry(QtCore.QRect(10, 120, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddBeschreibungsInput.setFont(font)
        self.AddBeschreibungsInput.setObjectName("AddBeschreibungsInput")
        self.AddDatumInput = QtWidgets.QCalendarWidget(parent=Add_Window)
        self.AddDatumInput.setGeometry(QtCore.QRect(50, 270, 312, 183))
        self.AddDatumInput.setObjectName("AddDatumInput")
        self.AddDatumText = QtWidgets.QLabel(parent=Add_Window)
        self.AddDatumText.setGeometry(QtCore.QRect(100, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddDatumText.setFont(font)
        self.AddDatumText.setObjectName("AddDatumText")
        self.AddPrioText = QtWidgets.QLabel(parent=Add_Window)
        self.AddPrioText.setGeometry(QtCore.QRect(60, 460, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddPrioText.setFont(font)
        self.AddPrioText.setObjectName("AddPrioText")
        self.AddStatusText = QtWidgets.QLabel(parent=Add_Window)
        self.AddStatusText.setGeometry(QtCore.QRect(250, 460, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddStatusText.setFont(font)
        self.AddStatusText.setObjectName("AddStatusText")
        self.AddPrioInput = QtWidgets.QComboBox(parent=Add_Window)
        self.AddPrioInput.setGeometry(QtCore.QRect(50, 510, 111, 31))
        self.AddPrioInput.setObjectName("AddPrioInput")
        self.AddPrioInput.addItem("")
        self.AddPrioInput.addItem("")
        self.AddPrioInput.addItem("")
        self.AddStatusInput = QtWidgets.QComboBox(parent=Add_Window)
        self.AddStatusInput.setGeometry(QtCore.QRect(230, 510, 111, 31))
        self.AddStatusInput.setObjectName("AddStatusInput")
        self.AddStatusInput.addItem("")
        self.AddStatusInput.addItem("")
        self.AddStatusInput.addItem("")
        self.AddExitButton = QtWidgets.QPushButton(parent=Add_Window, clicked=Add_Window.close)
        self.AddExitButton.setGeometry(QtCore.QRect(10, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddExitButton.setFont(font)
        self.AddExitButton.setObjectName("AddExitButton")
        self.AddSaveButton = QtWidgets.QPushButton(parent=Add_Window, clicked=lambda: self.get_info())
        self.AddSaveButton.setGeometry(QtCore.QRect(270, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddSaveButton.setFont(font)
        self.AddSaveButton.setObjectName("AddSaveButton")

        self.retranslateUi(Add_Window)
        QtCore.QMetaObject.connectSlotsByName(Add_Window)

    def retranslateUi(self, Add_Window):
        _translate = QtCore.QCoreApplication.translate
        Add_Window.setWindowTitle(_translate("Add_Window", "Dialog"))
        self.AddTitelText.setText(_translate("Add_Window", "Titel:"))
        self.AddBeschreibungsText.setText(_translate("Add_Window", "Beschreibung:"))
        self.AddBeschreibungsInput.setHtml(_translate("Add_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.AddDatumText.setText(_translate("Add_Window", "Geplantes Enddatum:"))
        self.AddPrioText.setText(_translate("Add_Window", "Priorität:"))
        self.AddStatusText.setText(_translate("Add_Window", "Status:"))
        self.AddPrioInput.setItemText(0, _translate("Add_Window", "1 - High"))
        self.AddPrioInput.setItemText(1, _translate("Add_Window", "2 - Medium"))
        self.AddPrioInput.setItemText(2, _translate("Add_Window", "3 - Low"))
        self.AddStatusInput.setItemText(0, _translate("Add_Window", "To Do"))
        self.AddStatusInput.setItemText(1, _translate("Add_Window", "In Arbeit"))
        self.AddStatusInput.setItemText(2, _translate("Add_Window", "Fertig"))
        self.AddExitButton.setText(_translate("Add_Window", "close"))
        self.AddSaveButton.setText(_translate("Add_Window", "save"))
