# Form implementation generated from reading ui file 'PyQt_UIs/Choose_edit.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Choose_to_edit(object):
    def setupUi(self, Choose_to_edit):
        Choose_to_edit.setObjectName("Choose_to_edit")
        Choose_to_edit.resize(316, 578)
        self.listWidget = QtWidgets.QListWidget(parent=Choose_to_edit)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 291, 511))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pushButton = QtWidgets.QPushButton(parent=Choose_to_edit)
        self.pushButton.setGeometry(QtCore.QRect(90, 540, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Choose_to_edit)
        QtCore.QMetaObject.connectSlotsByName(Choose_to_edit)

    def retranslateUi(self, Choose_to_edit):
        _translate = QtCore.QCoreApplication.translate
        Choose_to_edit.setWindowTitle(_translate("Choose_to_edit", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Choose_to_edit", "New Item"))
        item = self.listWidget.item(1)
        item.setText(_translate("Choose_to_edit", "New Item"))
        item = self.listWidget.item(2)
        item.setText(_translate("Choose_to_edit", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Choose_to_edit", "Edit"))
