# Form implementation generated from reading ui file 'PyQt_UIs/Edit_Window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Edit_Window(object):

    def set_date(self):
        self.calendarWidget.setSelectedDate(QtCore.QDate(2024, 6, 30))
        self.TitelLine.setText("Test")

    def setupUi(self, Edit_Window):
        Edit_Window.setObjectName("Edit_Window")
        Edit_Window.resize(416, 687)
        self.label_5 = QtWidgets.QLabel(parent=Edit_Window)
        self.label_5.setGeometry(QtCore.QRect(250, 460, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(parent=Edit_Window, clicked=lambda: Edit_Window.close())
        self.pushButton.setGeometry(QtCore.QRect(10, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(parent=Edit_Window)
        self.comboBox.setGeometry(QtCore.QRect(50, 510, 111, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(parent=Edit_Window)
        self.comboBox_2.setGeometry(QtCore.QRect(230, 510, 111, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.textEdit = QtWidgets.QTextEdit(parent=Edit_Window)
        self.textEdit.setGeometry(QtCore.QRect(10, 120, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(parent=Edit_Window)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Edit_Window)
        self.label_3.setGeometry(QtCore.QRect(100, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.TitelLine = QtWidgets.QLineEdit(parent=Edit_Window)
        self.TitelLine.setGeometry(QtCore.QRect(10, 40, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TitelLine.setFont(font)
        self.TitelLine.setText("")
        self.TitelLine.setObjectName("TitelLine")
        self.label = QtWidgets.QLabel(parent=Edit_Window)
        self.label.setGeometry(QtCore.QRect(10, -10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Edit_Window)
        self.calendarWidget.setGeometry(QtCore.QRect(50, 270, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_4 = QtWidgets.QLabel(parent=Edit_Window)
        self.label_4.setGeometry(QtCore.QRect(60, 460, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Edit_Window, clicked=lambda: self.set_date())
        self.pushButton_2.setGeometry(QtCore.QRect(270, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Edit_Window)
        QtCore.QMetaObject.connectSlotsByName(Edit_Window)

    def retranslateUi(self, Edit_Window):
        _translate = QtCore.QCoreApplication.translate
        Edit_Window.setWindowTitle(_translate("Edit_Window", "Dialog"))
        self.label_5.setText(_translate("Edit_Window", "Status:"))
        self.pushButton.setText(_translate("Edit_Window", "close"))
        self.comboBox.setItemText(0, _translate("Edit_Window", "1 - High"))
        self.comboBox.setItemText(1, _translate("Edit_Window", "2 - Medium"))
        self.comboBox.setItemText(2, _translate("Edit_Window", "3 - Low"))
        self.comboBox_2.setItemText(0, _translate("Edit_Window", "To Do"))
        self.comboBox_2.setItemText(1, _translate("Edit_Window", "In Arbeit"))
        self.comboBox_2.setItemText(2, _translate("Edit_Window", "Fertig"))
        self.textEdit.setHtml(_translate("Edit_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">TEst</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">testt</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Edit_Window", "Beschreibung:"))
        self.label_3.setText(_translate("Edit_Window", "Geplantes Enddatum:"))
        self.label.setText(_translate("Edit_Window", "Titel:"))
        self.label_4.setText(_translate("Edit_Window", "Priorität:"))
        self.pushButton_2.setText(_translate("Edit_Window", "save"))
