# Form implementation generated from reading ui file 'PyQt_UIs\Edit_Window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import Saving


class Ui_Edit_Window(object):
    def Loading(self):
        Saving.loadSave()

    def set_data(self):
        data = Saving.loadSave()

        try:
            task = data[0]["Tasks"]["Task1"]
        except Exception as e:
            print(f"Fehler: {e}")
            return

        self.EditTitelInput.setText(task.get("Task Title", ""))

        self.EditBeschreibungInput.setPlainText(task.get("Task Description", ""))

        RawEndDate = task.get("Task End Date", "")
        if RawEndDate:
            CorrectEndDate = QtCore.QDate.fromString(RawEndDate, "dd.MM.yyyy")
            self.EditEndKalender.setSelectedDate(CorrectEndDate)


        RawFokusDate = task.get("Task Fokus Date", "")
        if RawFokusDate:
            CorrectFokusDate = QtCore.QDate.fromString(RawFokusDate, "dd.MM.yyyy")
            self.EditFokusKalender.setSelectedDate(CorrectFokusDate)
            self.EditFokusCheck.setChecked(True)
        else:
            self.EditFokusCheck.setChecked(False)

        self.EditPrioAuswahl.setCurrentText(task.get("Task Priority", ""))

        self.EditStatusAuswahl.setCurrentText(task.get("Task Status", ""))

    def setupUi(self, Edit_Window):
        Edit_Window.setObjectName("Edit_Window")
        Edit_Window.resize(676, 687)
        self.EditStatusTitel = QtWidgets.QLabel(parent=Edit_Window)
        self.EditStatusTitel.setGeometry(QtCore.QRect(250, 480, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditStatusTitel.setFont(font)
        self.EditStatusTitel.setObjectName("EditStatusTitel")
        self.EditCloseButton = QtWidgets.QPushButton(parent=Edit_Window, clicked=lambda: Edit_Window.close())
        self.EditCloseButton.setGeometry(QtCore.QRect(280, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EditCloseButton.setFont(font)
        self.EditCloseButton.setObjectName("EditCloseButton")
        self.EditPrioAuswahl = QtWidgets.QComboBox(parent=Edit_Window)
        self.EditPrioAuswahl.setGeometry(QtCore.QRect(50, 510, 111, 31))
        self.EditPrioAuswahl.setObjectName("EditPrioAuswahl")
        self.EditPrioAuswahl.addItem("")
        self.EditPrioAuswahl.setItemText(0, "")
        self.EditPrioAuswahl.addItem("")
        self.EditPrioAuswahl.addItem("")
        self.EditPrioAuswahl.addItem("")
        self.EditStatusAuswahl = QtWidgets.QComboBox(parent=Edit_Window)
        self.EditStatusAuswahl.setGeometry(QtCore.QRect(230, 510, 111, 31))
        self.EditStatusAuswahl.setObjectName("EditStatusAuswahl")
        self.EditStatusAuswahl.addItem("")
        self.EditStatusAuswahl.setItemText(0, "")
        self.EditStatusAuswahl.addItem("")
        self.EditStatusAuswahl.addItem("")
        self.EditStatusAuswahl.addItem("")
        self.EditBeschreibungInput = QtWidgets.QTextEdit(parent=Edit_Window)
        self.EditBeschreibungInput.setGeometry(QtCore.QRect(10, 120, 651, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EditBeschreibungInput.setFont(font)
        self.EditBeschreibungInput.setObjectName("EditBeschreibungInput")
        self.EditBeschreibungTitel = QtWidgets.QLabel(parent=Edit_Window)
        self.EditBeschreibungTitel.setGeometry(QtCore.QRect(280, 70, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditBeschreibungTitel.setFont(font)
        self.EditBeschreibungTitel.setObjectName("EditBeschreibungTitel")
        self.EditEndDatumTitel = QtWidgets.QLabel(parent=Edit_Window)
        self.EditEndDatumTitel.setGeometry(QtCore.QRect(70, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditEndDatumTitel.setFont(font)
        self.EditEndDatumTitel.setObjectName("EditEndDatumTitel")
        self.EditTitelInput = QtWidgets.QLineEdit(parent=Edit_Window)
        self.EditTitelInput.setGeometry(QtCore.QRect(10, 40, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EditTitelInput.setFont(font)
        self.EditTitelInput.setText("")
        self.EditTitelInput.setObjectName("EditTitelInput")
        self.EditTitel = QtWidgets.QLabel(parent=Edit_Window)
        self.EditTitel.setGeometry(QtCore.QRect(310, -10, 51, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditTitel.setFont(font)
        self.EditTitel.setObjectName("EditTitel")
        self.EditEndKalender = QtWidgets.QCalendarWidget(parent=Edit_Window)
        self.EditEndKalender.setGeometry(QtCore.QRect(20, 270, 312, 183))
        self.EditEndKalender.setObjectName("EditEndKalender")
        self.EditPrioTitel = QtWidgets.QLabel(parent=Edit_Window)
        self.EditPrioTitel.setGeometry(QtCore.QRect(60, 480, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditPrioTitel.setFont(font)
        self.EditPrioTitel.setObjectName("EditPrioTitel")
        self.EditSaveButton = QtWidgets.QPushButton(parent=Edit_Window, clicked=lambda: self.set_data())
        self.EditSaveButton.setGeometry(QtCore.QRect(530, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EditSaveButton.setFont(font)
        self.EditSaveButton.setObjectName("EditSaveButton")
        self.EditFokusKalender = QtWidgets.QCalendarWidget(parent=Edit_Window)
        self.EditFokusKalender.setGeometry(QtCore.QRect(350, 270, 312, 183))
        self.EditFokusKalender.setObjectName("EditFokusKalender")
        self.EditFokusDatumTitel = QtWidgets.QLabel(parent=Edit_Window)
        self.EditFokusDatumTitel.setGeometry(QtCore.QRect(440, 210, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditFokusDatumTitel.setFont(font)
        self.EditFokusDatumTitel.setObjectName("EditFokusDatumTitel")
        self.EditFokusCheck = QtWidgets.QCheckBox(parent=Edit_Window)
        self.EditFokusCheck.setGeometry(QtCore.QRect(410, 510, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EditFokusCheck.setFont(font)
        self.EditFokusCheck.setObjectName("EditFokusCheck")
        self.EditDeleteButton = QtWidgets.QPushButton(parent=Edit_Window)
        self.EditDeleteButton.setGeometry(QtCore.QRect(10, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.EditDeleteButton.setFont(font)
        self.EditDeleteButton.setObjectName("EditDeleteButton")

        self.retranslateUi(Edit_Window)
        QtCore.QMetaObject.connectSlotsByName(Edit_Window)

    def retranslateUi(self, Edit_Window):
        _translate = QtCore.QCoreApplication.translate
        Edit_Window.setWindowTitle(_translate("Edit_Window", "Dialog"))
        self.EditStatusTitel.setText(_translate("Edit_Window", "Status:"))
        self.EditCloseButton.setText(_translate("Edit_Window", "Schließen"))
        self.EditPrioAuswahl.setItemText(1, _translate("Edit_Window", "1 - High"))
        self.EditPrioAuswahl.setItemText(2, _translate("Edit_Window", "2 - Medium"))
        self.EditPrioAuswahl.setItemText(3, _translate("Edit_Window", "3 - Low"))
        self.EditStatusAuswahl.setItemText(1, _translate("Edit_Window", "To Do"))
        self.EditStatusAuswahl.setItemText(2, _translate("Edit_Window", "In Arbeit"))
        self.EditStatusAuswahl.setItemText(3, _translate("Edit_Window", "Fertig"))
        self.EditBeschreibungInput.setHtml(_translate("Edit_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.EditBeschreibungTitel.setText(_translate("Edit_Window", "Beschreibung:"))
        self.EditEndDatumTitel.setText(_translate("Edit_Window", "Geplantes Enddatum:"))
        self.EditTitel.setText(_translate("Edit_Window", "Titel:"))
        self.EditPrioTitel.setText(_translate("Edit_Window", "Priorität:"))
        self.EditSaveButton.setText(_translate("Edit_Window", "Speichern"))
        self.EditFokusDatumTitel.setText(_translate("Edit_Window", "Fokus Datum:"))
        self.EditFokusCheck.setText(_translate("Edit_Window", "Fokus Datum ändern"))
        self.EditDeleteButton.setText(_translate("Edit_Window", "Löschen"))
