# Form implementation generated from reading ui file 'DesignedUIs/Edit_Window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Edit_Window(object):

    def set_date(self):
        self.EditDatumInput.setSelectedDate(QtCore.QDate(2024, 6, 30))
        self.EditTitelInput.setText("Test")


    def setupUi(self, Edit_Window):
        Edit_Window.setObjectName("Edit_Window")
        Edit_Window.resize(416, 687)
        self.EditStatusText = QtWidgets.QLabel(parent=Edit_Window)
        self.EditStatusText.setGeometry(QtCore.QRect(250, 460, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditStatusText.setFont(font)
        self.EditStatusText.setObjectName("EditStatusText")
        self.EditExitButton = QtWidgets.QPushButton(parent=Edit_Window, clicked=Edit_Window.close)
        self.EditExitButton.setGeometry(QtCore.QRect(10, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EditExitButton.setFont(font)
        self.EditExitButton.setObjectName("EditExitButton")
        self.EditPrioInput = QtWidgets.QComboBox(parent=Edit_Window)
        self.EditPrioInput.setGeometry(QtCore.QRect(50, 510, 111, 31))
        self.EditPrioInput.setObjectName("EditPrioInput")
        self.EditPrioInput.addItem("")
        self.EditPrioInput.addItem("")
        self.EditPrioInput.addItem("")
        self.EditStatusInput = QtWidgets.QComboBox(parent=Edit_Window)
        self.EditStatusInput.setGeometry(QtCore.QRect(230, 510, 111, 31))
        self.EditStatusInput.setObjectName("EditStatusInput")
        self.EditStatusInput.addItem("")
        self.EditStatusInput.addItem("")
        self.EditStatusInput.addItem("")
        self.EditBeschreibungInput = QtWidgets.QTextEdit(parent=Edit_Window)
        self.EditBeschreibungInput.setGeometry(QtCore.QRect(10, 120, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EditBeschreibungInput.setFont(font)
        self.EditBeschreibungInput.setObjectName("EditBeschreibungInput")
        self.EditBeschreibungText = QtWidgets.QLabel(parent=Edit_Window)
        self.EditBeschreibungText.setGeometry(QtCore.QRect(10, 70, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditBeschreibungText.setFont(font)
        self.EditBeschreibungText.setObjectName("EditBeschreibungText")
        self.EditDatumText = QtWidgets.QLabel(parent=Edit_Window)
        self.EditDatumText.setGeometry(QtCore.QRect(100, 210, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditDatumText.setFont(font)
        self.EditDatumText.setObjectName("EditDatumText")
        self.EditTitelInput = QtWidgets.QLineEdit(parent=Edit_Window)
        self.EditTitelInput.setGeometry(QtCore.QRect(10, 40, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EditTitelInput.setFont(font)
        self.EditTitelInput.setText("")
        self.EditTitelInput.setObjectName("EditTitelInput")
        self.EditTitelText = QtWidgets.QLabel(parent=Edit_Window)
        self.EditTitelText.setGeometry(QtCore.QRect(10, -10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditTitelText.setFont(font)
        self.EditTitelText.setObjectName("EditTitelText")
        self.EditDatumInput = QtWidgets.QCalendarWidget(parent=Edit_Window)
        self.EditDatumInput.setGeometry(QtCore.QRect(50, 270, 312, 183))
        self.EditDatumInput.setObjectName("EditDatumInput")
        self.EditPrioText = QtWidgets.QLabel(parent=Edit_Window)
        self.EditPrioText.setGeometry(QtCore.QRect(60, 460, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditPrioText.setFont(font)
        self.EditPrioText.setObjectName("EditPrioText")
        self.EditSaveButton = QtWidgets.QPushButton(parent=Edit_Window, clicked=lambda: self.set_date())
        self.EditSaveButton.setGeometry(QtCore.QRect(270, 640, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EditSaveButton.setFont(font)
        self.EditSaveButton.setObjectName("EditSaveButton")

        self.retranslateUi(Edit_Window)
        QtCore.QMetaObject.connectSlotsByName(Edit_Window)

    def retranslateUi(self, Edit_Window):
        _translate = QtCore.QCoreApplication.translate
        Edit_Window.setWindowTitle(_translate("Edit_Window", "Dialog"))
        self.EditStatusText.setText(_translate("Edit_Window", "Status:"))
        self.EditExitButton.setText(_translate("Edit_Window", "close"))
        self.EditPrioInput.setItemText(0, _translate("Edit_Window", "1 - High"))
        self.EditPrioInput.setItemText(1, _translate("Edit_Window", "2 - Medium"))
        self.EditPrioInput.setItemText(2, _translate("Edit_Window", "3 - Low"))
        self.EditStatusInput.setItemText(0, _translate("Edit_Window", "To Do"))
        self.EditStatusInput.setItemText(1, _translate("Edit_Window", "In Arbeit"))
        self.EditStatusInput.setItemText(2, _translate("Edit_Window", "Fertig"))
        self.EditBeschreibungInput.setHtml(_translate("Edit_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.EditBeschreibungText.setText(_translate("Edit_Window", "Beschreibung:"))
        self.EditDatumText.setText(_translate("Edit_Window", "Geplantes Enddatum:"))
        self.EditTitelText.setText(_translate("Edit_Window", "Titel:"))
        self.EditPrioText.setText(_translate("Edit_Window", "Priorität:"))
        self.EditSaveButton.setText(_translate("Edit_Window", "save"))
