# Form implementation generated from reading ui file 'DesignedUIs/Fokus_Main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from AddWindow import Ui_Add_Window
from EditWindow import Ui_Edit_Window
from FokusWindow import Ui_Fokus_Window
from ChooseEdit import Ui_Choose_to_edit

class Ui_Main_Window(object):
    def open_add_window(self):
        self.addWindow = QtWidgets.QDialog()
        self.ui = Ui_Add_Window()
        self.ui.setupUi(self.addWindow)
        self.addWindow.show()

    def open_edit_window(self):
        self.editWindow = QtWidgets.QDialog()
        self.ui = Ui_Edit_Window()
        self.ui.setupUi(self.editWindow)
        self.editWindow.show()

        #self.editWindow = QtWidgets.QDialog()
        #self.ui = Ui_Choose_to_edit()
        #self.ui.setupUi(self.editWindow)
        #self.editWindow.show()

    def open_fokus_window(self):
        self.fokusWindow = QtWidgets.QDialog()
        self.ui = Ui_Fokus_Window()
        self.ui.setupUi(self.fokusWindow)
        self.fokusWindow.show()


    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(617, 542)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main_Window.sizePolicy().hasHeightForWidth())
        Main_Window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.AddButton = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_add_window())
        self.AddButton.setGeometry(QtCore.QRect(10, 10, 291, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddButton.setFont(font)
        self.AddButton.setObjectName("AddButton")
        self.ShowButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.ShowButton.setGeometry(QtCore.QRect(310, 10, 291, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShowButton.sizePolicy().hasHeightForWidth())
        self.ShowButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ShowButton.setFont(font)
        self.ShowButton.setObjectName("ShowButton")
        self.EditButton = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_edit_window())
        self.EditButton.setGeometry(QtCore.QRect(10, 210, 291, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditButton.sizePolicy().hasHeightForWidth())
        self.EditButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.EditButton.setFont(font)
        self.EditButton.setObjectName("EditButton")
        self.DeleteButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(310, 210, 291, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteButton.sizePolicy().hasHeightForWidth())
        self.DeleteButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setObjectName("DeleteButton")
        self.FokusButton = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_fokus_window())
        self.FokusButton.setGeometry(QtCore.QRect(10, 400, 591, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FokusButton.sizePolicy().hasHeightForWidth())
        self.FokusButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FokusButton.setFont(font)
        self.FokusButton.setObjectName("FokusButton")
        Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 21))
        self.menubar.setObjectName("menubar")
        Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "MainWindow"))
        self.AddButton.setText(_translate("Main_Window", "Add"))
        self.ShowButton.setText(_translate("Main_Window", "Show"))
        self.EditButton.setText(_translate("Main_Window", "Edit"))
        self.DeleteButton.setText(_translate("Main_Window", "Delete"))
        self.FokusButton.setText(_translate("Main_Window", "Fokus"))
