# Form implementation generated from reading ui file 'PyQt_UIs\Fokus_Main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from AddWindow import Ui_Add_Window
from EditWindow import Ui_Edit_Window
from FokusWindow import Ui_Fokus_Window


class Ui_Main_Window(object):
        
    def open_add_window(self):
        self.addWindow = QtWidgets.QDialog()
        self.ui = Ui_Add_Window()
        self.ui.setupUi(self.addWindow)
        self.addWindow.show()

    def open_edit_window(self):
        self.editWindow = QtWidgets.QDialog()
        self.ui = Ui_Edit_Window()
        self.ui.setupUi(self.editWindow)
        self.editWindow.show()

        #self.editWindow = QtWidgets.QDialog()
        #self.ui = Ui_Choose_to_edit()
        #self.ui.setupUi(self.editWindow)
        #self.editWindow.show()

    def open_fokus_window(self):
        self.fokusWindow = QtWidgets.QDialog()
        self.ui = Ui_Fokus_Window()
        self.ui.setupUi(self.fokusWindow)
        self.fokusWindow.show()


    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(617, 336)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main_Window.sizePolicy().hasHeightForWidth())
        Main_Window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.AddWindowButton = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_add_window())
        self.AddWindowButton.setGeometry(QtCore.QRect(10, 10, 291, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddWindowButton.sizePolicy().hasHeightForWidth())
        self.AddWindowButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddWindowButton.setFont(font)
        self.AddWindowButton.setObjectName("AddWindowButton")
        self.EditWindowButton = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_edit_window())
        self.EditWindowButton.setGeometry(QtCore.QRect(310, 10, 291, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EditWindowButton.sizePolicy().hasHeightForWidth())
        self.EditWindowButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.EditWindowButton.setFont(font)
        self.EditWindowButton.setObjectName("EditWindowButton")
        self.FokusWindowButton = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_fokus_window())
        self.FokusWindowButton.setGeometry(QtCore.QRect(10, 210, 591, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FokusWindowButton.sizePolicy().hasHeightForWidth())
        self.FokusWindowButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FokusWindowButton.setFont(font)
        self.FokusWindowButton.setObjectName("FokusWindowButton")
        Main_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "MainWindow"))
        self.AddWindowButton.setText(_translate("Main_Window", "Add"))
        self.EditWindowButton.setText(_translate("Main_Window", "Edit"))
        self.FokusWindowButton.setText(_translate("Main_Window", "Fokus"))
