# Form implementation generated from reading ui file 'DesignedUIs/Fokus_Window.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import Saving


class Ui_Fokus_Window(object):
    def get_Fokus(self):
        Fokus1 = {
            "Fokus Titel": self.FokusTitelInput1.text(),
            "Fokus Beschreibung": self.FokusBeschreibungInput1.toPlainText(),
            "Fokus Priorität": self.FokusPrioInput1.currentText()
        }
        Fokus2 = {
            "Fokus Titel": self.FokusTitelInput3.text(),
            "Fokus Beschreibung": self.FokusBeschreibungInput2.toPlainText(),
            "Fokus Priorität": self.FokusPrioInput2.currentText()
        }
        Fokus3 = {
            "Fokus Titel": self.FokusTitelInput3_2.text(),
            "Fokus Beschreibung": self.FokusBeschreibungInput3.toPlainText(),
            "Fokus Priorität": self.FokusPrioInput3.currentText()
        }
        FullFokusData = {
            "Fokus 1": Fokus1,
            "Fokus 2": Fokus2,
            "Fokus 3": Fokus3
        }
        Saving.FokusSave(FullFokusData)

    def setupUi(self, Fokus_Window):
        Fokus_Window.setObjectName("Fokus_Window")
        Fokus_Window.resize(429, 843)
        self.FokusBeschreibungInput1 = QtWidgets.QTextEdit(parent=Fokus_Window)
        self.FokusBeschreibungInput1.setGeometry(QtCore.QRect(10, 90, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FokusBeschreibungInput1.setFont(font)
        self.FokusBeschreibungInput1.setObjectName("FokusBeschreibungInput1")
        self.FokusTitelInput1 = QtWidgets.QLineEdit(parent=Fokus_Window)
        self.FokusTitelInput1.setGeometry(QtCore.QRect(10, 40, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FokusTitelInput1.setFont(font)
        self.FokusTitelInput1.setObjectName("FokusTitelInput1")
        self.FokusTitelText1 = QtWidgets.QLabel(parent=Fokus_Window)
        self.FokusTitelText1.setGeometry(QtCore.QRect(10, -10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FokusTitelText1.setFont(font)
        self.FokusTitelText1.setObjectName("FokusTitelText1")
        self.FokusPrioInput1 = QtWidgets.QComboBox(parent=Fokus_Window)
        self.FokusPrioInput1.setGeometry(QtCore.QRect(10, 200, 111, 31))
        self.FokusPrioInput1.setObjectName("FokusPrioInput1")
        self.FokusPrioInput1.addItem("")
        self.FokusPrioInput1.addItem("")
        self.FokusPrioInput1.addItem("")
        self.FokusTitelText2 = QtWidgets.QLabel(parent=Fokus_Window)
        self.FokusTitelText2.setGeometry(QtCore.QRect(10, 240, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FokusTitelText2.setFont(font)
        self.FokusTitelText2.setObjectName("FokusTitelText2")
        self.FokusBeschreibungInput2 = QtWidgets.QTextEdit(parent=Fokus_Window)
        self.FokusBeschreibungInput2.setGeometry(QtCore.QRect(10, 340, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FokusBeschreibungInput2.setFont(font)
        self.FokusBeschreibungInput2.setObjectName("FokusBeschreibungInput2")
        self.FokusPrioInput2 = QtWidgets.QComboBox(parent=Fokus_Window)
        self.FokusPrioInput2.setGeometry(QtCore.QRect(10, 450, 111, 31))
        self.FokusPrioInput2.setObjectName("FokusPrioInput2")
        self.FokusPrioInput2.addItem("")
        self.FokusPrioInput2.addItem("")
        self.FokusPrioInput2.addItem("")
        self.FokusTitelInput3 = QtWidgets.QLineEdit(parent=Fokus_Window)
        self.FokusTitelInput3.setGeometry(QtCore.QRect(10, 290, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FokusTitelInput3.setFont(font)
        self.FokusTitelInput3.setObjectName("FokusTitelInput3")
        self.FokusPrioInput3 = QtWidgets.QComboBox(parent=Fokus_Window)
        self.FokusPrioInput3.setGeometry(QtCore.QRect(10, 700, 111, 31))
        self.FokusPrioInput3.setObjectName("FokusPrioInput3")
        self.FokusPrioInput3.addItem("")
        self.FokusPrioInput3.addItem("")
        self.FokusPrioInput3.addItem("")
        self.FokusTitelText3 = QtWidgets.QLabel(parent=Fokus_Window)
        self.FokusTitelText3.setGeometry(QtCore.QRect(10, 490, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FokusTitelText3.setFont(font)
        self.FokusTitelText3.setObjectName("FokusTitelText3")
        self.FokusTitelInput3_2 = QtWidgets.QLineEdit(parent=Fokus_Window)
        self.FokusTitelInput3_2.setGeometry(QtCore.QRect(10, 540, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FokusTitelInput3_2.setFont(font)
        self.FokusTitelInput3_2.setObjectName("FokusTitelInput3_2")
        self.FokusBeschreibungInput3 = QtWidgets.QTextEdit(parent=Fokus_Window)
        self.FokusBeschreibungInput3.setGeometry(QtCore.QRect(10, 590, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FokusBeschreibungInput3.setFont(font)
        self.FokusBeschreibungInput3.setObjectName("FokusBeschreibungInput3")
        self.SaveButton = QtWidgets.QPushButton(parent=Fokus_Window, clicked=self.get_Fokus)
        self.SaveButton.setGeometry(QtCore.QRect(290, 790, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.SaveCloseButton = QtWidgets.QPushButton(parent=Fokus_Window, clicked=lambda: [self.get_Fokus(), Fokus_Window.close()])
        self.SaveCloseButton.setGeometry(QtCore.QRect(140, 790, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SaveCloseButton.setFont(font)
        self.SaveCloseButton.setObjectName("SaveCloseButton")

        self.retranslateUi(Fokus_Window)
        QtCore.QMetaObject.connectSlotsByName(Fokus_Window)

    def retranslateUi(self, Fokus_Window):
        _translate = QtCore.QCoreApplication.translate
        Fokus_Window.setWindowTitle(_translate("Fokus_Window", "Dialog"))
        self.FokusBeschreibungInput1.setHtml(_translate("Fokus_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beschreibung für Fokus 1</p></body></html>"))
        self.FokusTitelInput1.setText(_translate("Fokus_Window", "Fokus Titel 1"))
        self.FokusTitelText1.setText(_translate("Fokus_Window", "Fokus 1:"))
        self.FokusPrioInput1.setItemText(0, _translate("Fokus_Window", "1 - High"))
        self.FokusPrioInput1.setItemText(1, _translate("Fokus_Window", "2 - Medium"))
        self.FokusPrioInput1.setItemText(2, _translate("Fokus_Window", "3 - Low"))
        self.FokusTitelText2.setText(_translate("Fokus_Window", "Fokus 2:"))
        self.FokusBeschreibungInput2.setHtml(_translate("Fokus_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beschreibung für Fokus 2</p></body></html>"))
        self.FokusPrioInput2.setItemText(0, _translate("Fokus_Window", "1 - High"))
        self.FokusPrioInput2.setItemText(1, _translate("Fokus_Window", "2 - Medium"))
        self.FokusPrioInput2.setItemText(2, _translate("Fokus_Window", "3 - Low"))
        self.FokusTitelInput3.setText(_translate("Fokus_Window", "Fokus Titel 2"))
        self.FokusPrioInput3.setItemText(0, _translate("Fokus_Window", "1 - High"))
        self.FokusPrioInput3.setItemText(1, _translate("Fokus_Window", "2 - Medium"))
        self.FokusPrioInput3.setItemText(2, _translate("Fokus_Window", "3 - Low"))
        self.FokusTitelText3.setText(_translate("Fokus_Window", "Fokus 3:"))
        self.FokusTitelInput3_2.setText(_translate("Fokus_Window", "Fokus Titel 3"))
        self.FokusBeschreibungInput3.setHtml(_translate("Fokus_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beschreibung für Fokus 3</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.SaveButton.setText(_translate("Fokus_Window", "save"))
        self.SaveCloseButton.setText(_translate("Fokus_Window", "save and close"))
