from PyQt6 import QtCore, QtGui, QtWidgets

from AddWindow import Ui_Add_Window
from EditWindow import Ui_Edit_Window
from FokusWindow import Ui_Fokus_Window
from ChooseEdit import Ui_Choose_to_edit


class Ui_Main_Window(object):
    def open_add_window(self):
        self.addWindow = QtWidgets.QDialog()
        self.ui = Ui_Add_Window()
        self.ui.setupUi(self.addWindow)
        self.addWindow.show()

    def open_edit_window(self):
        self.editWindow = QtWidgets.QDialog()
        self.ui = Ui_Edit_Window()
        self.ui.setupUi(self.editWindow)
        self.editWindow.show()

        #self.editWindow = QtWidgets.QDialog()
        #self.ui = Ui_Choose_to_edit()
        #self.ui.setupUi(self.editWindow)
        #self.editWindow.show()

    def open_fokus_window(self):
        self.fokusWindow = QtWidgets.QDialog()
        self.ui = Ui_Fokus_Window()
        self.ui.setupUi(self.fokusWindow)
        self.fokusWindow.show()

    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(617, 542)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main_Window.sizePolicy().hasHeightForWidth())
        Main_Window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_add_window())
        self.toolButton.setGeometry(QtCore.QRect(10, 10, 291, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(310, 10, 291, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_edit_window())
        self.toolButton_3.setGeometry(QtCore.QRect(10, 210, 291, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setObjectName("toolButton_3")
        self.toolButton_4 = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(310, 210, 291, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_4.sizePolicy().hasHeightForWidth())
        self.toolButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(parent=self.centralwidget, clicked=lambda: self.open_fokus_window())
        self.toolButton_5.setGeometry(QtCore.QRect(10, 400, 591, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_5.sizePolicy().hasHeightForWidth())
        self.toolButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setObjectName("toolButton_5")
        Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 21))
        self.menubar.setObjectName("menubar")
        Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def retranslateUi(self, Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "MainWindow"))
        self.toolButton.setText(_translate("Main_Window", "Add"))
        self.toolButton_2.setText(_translate("Main_Window", "Show"))
        self.toolButton_3.setText(_translate("Main_Window", "Edit"))
        self.toolButton_4.setText(_translate("Main_Window", "Delete"))
        self.toolButton_5.setText(_translate("Main_Window", "Fokus"))

