# Form implementation generated from reading ui file 'PyQt_UIs/Fokus_Window.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Fokus_Window(object):
    def setupUi(self, Fokus_Window):
        Fokus_Window.setObjectName("Fokus_Window")
        Fokus_Window.resize(429, 843)
        self.textEdit = QtWidgets.QTextEdit(parent=Fokus_Window)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=Fokus_Window)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Fokus_Window)
        self.label.setGeometry(QtCore.QRect(10, -10, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=Fokus_Window)
        self.comboBox.setGeometry(QtCore.QRect(10, 200, 111, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=Fokus_Window)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Fokus_Window)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 340, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.comboBox_2 = QtWidgets.QComboBox(parent=Fokus_Window)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 450, 111, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Fokus_Window)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 290, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_3 = QtWidgets.QComboBox(parent=Fokus_Window)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 700, 111, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_4 = QtWidgets.QLabel(parent=Fokus_Window)
        self.label_4.setGeometry(QtCore.QRect(10, 490, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Fokus_Window)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 540, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=Fokus_Window)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 590, 391, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Fokus_Window)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 790, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(parent=Fokus_Window)
        self.pushButton.setGeometry(QtCore.QRect(140, 790, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Fokus_Window)
        QtCore.QMetaObject.connectSlotsByName(Fokus_Window)

    def retranslateUi(self, Fokus_Window):
        _translate = QtCore.QCoreApplication.translate
        Fokus_Window.setWindowTitle(_translate("Fokus_Window", "Dialog"))
        self.textEdit.setHtml(_translate("Fokus_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beschreibung für Fokus 1</p></body></html>"))
        self.lineEdit.setText(_translate("Fokus_Window", "Fokus Titel 1"))
        self.label.setText(_translate("Fokus_Window", "Fokus 1:"))
        self.comboBox.setItemText(0, _translate("Fokus_Window", "1 - High"))
        self.comboBox.setItemText(1, _translate("Fokus_Window", "2 - Medium"))
        self.comboBox.setItemText(2, _translate("Fokus_Window", "3 - Low"))
        self.label_3.setText(_translate("Fokus_Window", "Fokus 2:"))
        self.textEdit_2.setHtml(_translate("Fokus_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beschreibung für Fokus 2</p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("Fokus_Window", "1 - High"))
        self.comboBox_2.setItemText(1, _translate("Fokus_Window", "2 - Medium"))
        self.comboBox_2.setItemText(2, _translate("Fokus_Window", "3 - Low"))
        self.lineEdit_2.setText(_translate("Fokus_Window", "Fokus Titel 2"))
        self.comboBox_3.setItemText(0, _translate("Fokus_Window", "1 - High"))
        self.comboBox_3.setItemText(1, _translate("Fokus_Window", "2 - Medium"))
        self.comboBox_3.setItemText(2, _translate("Fokus_Window", "3 - Low"))
        self.label_4.setText(_translate("Fokus_Window", "Fokus 3:"))
        self.lineEdit_3.setText(_translate("Fokus_Window", "Fokus Titel 3"))
        self.textEdit_3.setHtml(_translate("Fokus_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Beschreibung für Fokus 3</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("Fokus_Window", "save"))
        self.pushButton.setText(_translate("Fokus_Window", "save and close"))
